AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Create a policy for assuming a role in the bucket owner's account.

Parameters:
  RoleArn:
    Description: The ARN of the role of another account to be assumed to for reading S3 objects
    Type: String

Resources:
  IamPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy for assuming role"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Resource: !Ref RoleArn
