# Stack name: K-SFN-Demo-1
# CFN Tag: Project K-SFN-Demo-1
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Step Function and Lambda function with dummy content.

Parameters:
  ApigName:
    Description: Name of the API to create
    Type: String
    Default: K-SFN-API
  FunctionAName:
    Description: Name of the Lambda function to be created or updated.
    Type: String
    Default: K-SFN-Function-A
  FunctionBName:
    Description: Name of the Lambda function to be created or updated.
    Type: String
    Default: K-SFN-Function-B
  LogRetention:
    Description: Days to keep application logs
    Type: Number
    Default: 1
  StateMachineName:
    Description: Name of the State Machine to create.
    Type: String
    Default: K-SFN-StateMachine

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: !Sub ${FunctionAName}-ExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              # This function will be updated through CI/CD
              return "Lambda version 1"
      FunctionName: !Ref FunctionAName
      Handler: index.lambda_handler
      MemorySize: 1024
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.7
      Timeout: 900
      TracingConfig:
        Mode: Active
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunction}
      RetentionInDays: !Ref LogRetention

  LambdaFunctionB:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              # This function will be updated through CI/CD
              return "Lambda version 1"
      FunctionName: !Ref FunctionBName
      Handler: index.lambda_handler
      MemorySize: 1024
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.7
      Timeout: 900
      TracingConfig:
        Mode: Active
  LambdaLogGroupB:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionB}
      RetentionInDays: !Ref LogRetention

  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${StateMachineName}-ExecutionRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - lambda:ListFunctions
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionAName}*"
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"
              - Effect: Allow
                Action:
                  - xray:Put*
                Resource: "*"
      RoleName: !Sub ${StateMachineName}-ExecuteRole

  StateMachineLogGroupBlue:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${StateMachineName}-Blue-Logs
      RetentionInDays: !Ref LogRetention
  StateMachineBlue:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Hello World example using an AWS Lambda function",
              "StartAt": "HelloWorld",
              "States": {
                "HelloWorld": {
                  "Type": "Task",
                  "Resource": "${lambdaArn}:blue",
                  "End": true
                }
              }
            }
          - {lambdaArn: !GetAtt LambdaFunction.Arn}
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroupBlue.Arn
        IncludeExecutionData: true
        Level: ERROR
      RoleArn: !GetAtt StateMachineExecutionRole.Arn
      StateMachineName: !Sub ${StateMachineName}-Blue
      StateMachineType: STANDARD
      TracingConfiguration:
        Enabled: true

  StateMachineLogGroupGreen:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${StateMachineName}-Green-Logs
      RetentionInDays: !Ref LogRetention
  StateMachineGreen:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Hello World example using an AWS Lambda function",
              "StartAt": "HelloWorld",
              "States": {
                "HelloWorld": {
                  "Type": "Task",
                  "Resource": "${lambdaArn}:green",
                  "End": true
                }
              }
            }
          - {lambdaArn: !GetAtt LambdaFunction.Arn}
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroupGreen.Arn
        IncludeExecutionData: true
        Level: ERROR
      RoleArn: !GetAtt StateMachineExecutionRole.Arn
      StateMachineName: !Sub ${StateMachineName}-Green
      StateMachineType: STANDARD
      TracingConfiguration:
        Enabled: true

  StateMachineExecutePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed Policy for starting new execution
      ManagedPolicyName: !Sub ${StateMachineName}-ExecutionRolePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionAName}*"
          - Effect: Allow
            Action:
              - states:StartExecution
              - states:DescribeExecution
            Resource:
              - !Ref StateMachineBlue
              - !Sub "${StateMachineBlue}:*"
              - !Ref StateMachineGreen
              - !Sub "${StateMachineGreen}:*"

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApigName
      Description: !Ref ApigName
      FailOnWarnings: true

  ApigExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ApigName}-APIGatewayToStepFunctions
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FunctionBName}*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
